/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllOrdersDialog.java
 *
 * Created on Feb 13, 2012, 7:12:35 PM
 */
package stefanpresentationlayer.dialogs;

import java.awt.*;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.tree.TreePath;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Workbook;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingx.JXDatePicker;
import stefan.business.DesignManager;
import stefan.business.ExcelManager;
import stefan.business.OrderManager;
import stefan.business.objects.Design;
import stefan.business.objects.Order;
import stefan.data.Orderitems;
import stefan.data.Orders;
import stefanpresentationlayer.MyTreeNode;
import stefanpresentationlayer.MyTreeTableModel;
import stefanpresentationlayer.OrdersTableCellRenderer;
import stefanpresentationlayer.StefanPresentationLayerView;
import stefanpresentationlayer.models.OrderType;

/**
 *
 * @author Matija
 */
public class AllOrdersDialog extends javax.swing.JDialog {

   
    private MyTreeTableModel treeTableModel;

    private List<OrderType> bpTypes = ObservableCollections.observableList(new ArrayList<OrderType>());
    private OrderType selectedBpType = OrderType.All;

    /** Creates new form AllOrdersDialog */
    public AllOrdersDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);              
        initComponents(); 
        refreshTreeData();
        setTitle("Pregled Narudžbi");

        bpTypes.add(OrderType.All);
        bpTypes.add(OrderType.Internal);
        bpTypes.add(OrderType.External);
    }
  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTable1 = new org.jdesktop.swingx.JXTreeTable();
        closeBtn = new javax.swing.JButton();
        _btnDeleteOrder = new javax.swing.JButton();
        _btnDeleteOrderItem = new javax.swing.JButton();
        jButtonUpdateShippingDate = new javax.swing.JButton();
        jButtonChaneQuantity = new javax.swing.JButton();
        btnChangePosition = new javax.swing.JButton();
        bpTypeFilterCBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        printExternalOrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(AllOrdersDialog.class);
        jXTreeTable1.setFont(resourceMap.getFont("jXTreeTable1.font")); // NOI18N
        jXTreeTable1.setName("jXTreeTable1"); // NOI18N
        jXTreeTable1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jXTreeTable1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jXTreeTable1);

        closeBtn.setText(resourceMap.getString("closeBtn.text")); // NOI18N
        closeBtn.setName("closeBtn"); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        _btnDeleteOrder.setText(resourceMap.getString("_btnDeleteOrder.text")); // NOI18N
        _btnDeleteOrder.setName("_btnDeleteOrder"); // NOI18N
        _btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDeleteOrderActionPerformed(evt);
            }
        });

        _btnDeleteOrderItem.setText(resourceMap.getString("_btnDeleteOrderItem.text")); // NOI18N
        _btnDeleteOrderItem.setName("_btnDeleteOrderItem"); // NOI18N
        _btnDeleteOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDeleteOrderItemActionPerformed(evt);
            }
        });

        jButtonUpdateShippingDate.setText(resourceMap.getString("jButtonUpdateShippingDate.text")); // NOI18N
        jButtonUpdateShippingDate.setName("jButtonUpdateShippingDate"); // NOI18N
        jButtonUpdateShippingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateShippingDateActionPerformed(evt);
            }
        });

        jButtonChaneQuantity.setText(resourceMap.getString("jButtonChaneQuantity.text")); // NOI18N
        jButtonChaneQuantity.setName("jButtonChaneQuantity"); // NOI18N
        jButtonChaneQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChaneQuantityActionPerformed(evt);
            }
        });

        btnChangePosition.setText(resourceMap.getString("btnChangePosition.text")); // NOI18N
        btnChangePosition.setActionCommand(resourceMap.getString("btnChangePosition.actionCommand")); // NOI18N
        btnChangePosition.setName("btnChangePosition"); // NOI18N
        btnChangePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePositionActionPerformed(evt);
            }
        });

        bpTypeFilterCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bpTypeFilterCBox.setName("bpTypeFilterCBox"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bpTypes}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, bpTypeFilterCBox);
        bindingGroup.addBinding(jComboBoxBinding);

        bpTypeFilterCBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bpTypeFilterCBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        printExternalOrderButton.setText(resourceMap.getString("printExternalOrderButton.text")); // NOI18N
        printExternalOrderButton.setEnabled(false);
        printExternalOrderButton.setName("printExternalOrderButton"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jXTreeTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedRows.length != 0}"), printExternalOrderButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"), "");
        bindingGroup.addBinding(binding);

        printExternalOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printExternalOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_btnDeleteOrder)
                        .addGap(18, 18, 18)
                        .addComponent(_btnDeleteOrderItem)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateShippingDate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChaneQuantity)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangePosition)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpTypeFilterCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printExternalOrderButton))
                    .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnDeleteOrder)
                    .addComponent(_btnDeleteOrderItem)
                    .addComponent(jButtonUpdateShippingDate)
                    .addComponent(jButtonChaneQuantity)
                    .addComponent(btnChangePosition)
                    .addComponent(jLabel1)
                    .addComponent(bpTypeFilterCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printExternalOrderButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private List<Order> allItems = new ArrayList<Order>();
    private List<Order> filteredItems = new ArrayList<Order>();
    private void refreshTreeData(){
        OrderManager manager = new OrderManager();
        allItems = manager.getOrders();

        treeTableModel = new MyTreeTableModel(allItems);
        jXTreeTable1.setDefaultRenderer(Object.class, new OrdersTableCellRenderer());
        jXTreeTable1.setTreeTableModel(treeTableModel);
        jXTreeTable1.expandAll();
    }

    private void filterTreeData() {
        filteredItems.clear();

        switch (this.selectedBpType) {
            case Internal: {
                for (Order o : this.allItems) {
                    if (!o.getIsBusinessPartnerExternal())
                        filteredItems.add(o);
                }
                break;
            }

            case External: {
                for (Order o : this.allItems) {
                    if (o.getIsBusinessPartnerExternal())
                        filteredItems.add(o);
                }
                break;
            }

            case All:
            default: {
                filteredItems.addAll(this.allItems);
                break;
            }
        }

        treeTableModel = new MyTreeTableModel(filteredItems);
        jXTreeTable1.setDefaultRenderer(Object.class, new OrdersTableCellRenderer());
        jXTreeTable1.setTreeTableModel(treeTableModel);
        jXTreeTable1.expandAll();
    }
    
    
    private void _btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDeleteOrderActionPerformed
        int row = jXTreeTable1.getSelectedRow();
        if (row!=-1)
        {            
            TreePath tp = jXTreeTable1.getPathForRow(row);
            MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
            OrderManager manager=new OrderManager();
            manager.deleteOrder(node.getOrderId());   
            
            refreshTreeData();
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite narudžbu.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event__btnDeleteOrderActionPerformed

    private void _btnDeleteOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDeleteOrderItemActionPerformed
        int row = jXTreeTable1.getSelectedRow();
        if (row!=-1)
        {
            TreePath tp = jXTreeTable1.getPathForRow(row);
            MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();            
            if (node.getOrderItemId()!=null)
            {
                OrderManager manager=new OrderManager();
                manager.deleteOrderItem(node.getOrderItemId());
                
                refreshTreeData();             
            }                    
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;        
        }        
    }//GEN-LAST:event__btnDeleteOrderItemActionPerformed

private void jButtonUpdateShippingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateShippingDateActionPerformed

    int row = jXTreeTable1.getSelectedRow();
    if (row != -1)
    {
        TreePath tp = jXTreeTable1.getPathForRow(row);
        MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
        if (node.getOrderItemId() != null)
        {            
            JXDatePicker jd = new JXDatePicker();
            jd.getMonthView().setPreferredColumnCount(2);
            jd.getMonthView().setPreferredRowCount(2);
            jd.getMonthView().setFirstDayOfWeek(2);
            jd.getMonthView().setShowingWeekNumber(true);  
            jd.getMonthView().getSelectionModel().setMinimalDaysInFirstWeek(4);
            jd.setFormats(new String[] {"d.M.yyyy."});            
            String message ="Odaberite novi datum isporuke:\n";
            Object[] params = {message,jd};
            JOptionPane.showConfirmDialog(null,params,"Datum Isporuke", JOptionPane.PLAIN_MESSAGE);
            Date newShippingDate = jd.getDate();
            if (newShippingDate == null)
            {
                return;
            }            
            
            OrderManager manager = new OrderManager();
            manager.UpdateOrderItemShippingDate(node.getOrderItemId(), newShippingDate);
                      
            refreshTreeData();    
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
    }
    else {
        JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;        
    }
}//GEN-LAST:event_jButtonUpdateShippingDateActionPerformed

private void jButtonChaneQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChaneQuantityActionPerformed
    int row = jXTreeTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    TreePath tp = jXTreeTable1.getPathForRow(row);
    MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
    if (node.getOrderItemId() == null)
        return;

    OrderManager om = new OrderManager();
    Orders o = om.getOrderById(node.getOrderId());
    if (o.getBusinessPartnerId().getIsExternalSource()) {
        Orderitems oi = om.getOrderItemById(node.getOrderItemId());

        DesignManager dm = new DesignManager();
        Design d = dm.mapData(dm.GetDesignsByDBId(node.getDesignId()));

        NewExternalOrderItemJDialog editOrderItemDiag = new NewExternalOrderItemJDialog(null, true, d);
        editOrderItemDiag.setQuantityValue(node.getQuantityOrdered());
        editOrderItemDiag.setPricePerPartValue(oi.getPricePerPartOverride().doubleValue());

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        editOrderItemDiag.setBounds(
            dim.width / 2 - editOrderItemDiag.getWidth() / 2,
            dim.height / 2 - editOrderItemDiag.getHeight() / 2,

            editOrderItemDiag.getWidth(),
            editOrderItemDiag.getHeight()
        );

        editOrderItemDiag.setTitle("Upis količine");
        editOrderItemDiag.setVisible(true);

        if (!editOrderItemDiag.isOkExitStatus())
            return;

        int qty = editOrderItemDiag.getQuantity();
        BigDecimal pricePerPartOvr = new BigDecimal(editOrderItemDiag.getPricePerPartValue()).setScale(2, RoundingMode.HALF_UP);

        om.UpdateOrderItemQuantityOrdered(oi.getIdOrderItems(), qty, pricePerPartOvr);
        refreshTreeData();
        return;
    }

    boolean isAnswerOk = false;
    int parts = 0;

    while (!isAnswerOk) {
        String partsString = JOptionPane.showInputDialog(null, "Koliko komada?", "Broj komada", JOptionPane.QUESTION_MESSAGE);
        if (partsString == null) {
            break;
        } else {
           try {
                parts = Integer.valueOf(partsString);
                if (parts <= 0) {
                    JOptionPane.showMessageDialog(null, "Unesite više od 0 komada");
                }
                else {
                    isAnswerOk = true;
                }
           }
           catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null, "Unesite samo brojeve");
           }
        }
    }

    if (isAnswerOk){
        om.UpdateOrderItemQuantityOrdered(node.getOrderItemId(), parts);

        refreshTreeData();
    }
}//GEN-LAST:event_jButtonChaneQuantityActionPerformed

private void btnChangePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePositionActionPerformed
     int row = jXTreeTable1.getSelectedRow();
    if (row != -1)
    {
        TreePath tp = jXTreeTable1.getPathForRow(row);
        MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
        if (node.getOrderItemId() != null)
        {
            boolean isAnswerOk = false;            
            String partAsStringFinal = null;
             
            while (!isAnswerOk) {
                String  partsString = (String)JOptionPane.showInputDialog(null, "Unesite novu poziciju stavke?", "Pozicija stavke", JOptionPane.QUESTION_MESSAGE, null, null, node.getPosition());
                if (partsString == null) {                    
                    break;
                } else {
                   try {
                        Integer newPosition = Integer.valueOf(partsString);
                        if (newPosition <= 0) {
                            JOptionPane.showMessageDialog(null, "Pozicija mora biti pozitivan broj veći od 0");
                        }
                        else {
                            isAnswerOk = true;                           
                            partAsStringFinal = String.format("%05d", newPosition);
                        }                     
                   }
                   catch (NumberFormatException e) {
                       JOptionPane.showMessageDialog(null, "Unesite samo brojeve");
                   }
                }               
            }
            
            if (isAnswerOk){
                OrderManager manager = new OrderManager();
                manager.UpdateOrderItemPosition(node.getOrderItemId(), partAsStringFinal);
            
                refreshTreeData();  
            }
        }
    }
    else {
        JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;        
    }
}//GEN-LAST:event_btnChangePositionActionPerformed

private void bpTypeFilterCBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bpTypeFilterCBoxItemStateChanged
        Object it = evt.getItem();
        if (it instanceof OrderType && evt.getStateChange() == ItemEvent.SELECTED) {
            selectedBpType = (OrderType)it;
            filterTreeData();
        }
}//GEN-LAST:event_bpTypeFilterCBoxItemStateChanged

    private void printExternalOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printExternalOrderButtonActionPerformed
        int[] rows = jXTreeTable1.getSelectedRows();
        if (rows.length == 0)
            return;

        List<Integer> orders = new ArrayList<Integer>();
        for (int rowIdx : rows) {
            TreePath tp = jXTreeTable1.getPathForRow(rowIdx);
            Object o = tp.getLastPathComponent();

            if (!(o instanceof MyTreeNode))
                continue;

            MyTreeNode tn = (MyTreeNode)o;

            orders.add(tn.getOrderId());
        }

        if (orders.isEmpty())
            return;

        Workbook workbook = new HSSFWorkbook();
        ExcelManager excelManager = new ExcelManager(workbook);
        try {
            excelManager.createExternalOrderPirnt(orders.get(0));
        } catch (IOException ex) {
            Logger.getLogger(StefanPresentationLayerView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printExternalOrderButtonActionPerformed

    private void jXTreeTable1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jXTreeTable1ValueChanged
        int[] selectedRows = jXTreeTable1.getSelectedRows();
        printExternalOrderButton.setEnabled(selectedRows.length > 0);
        for (int selectedRow : selectedRows) {
            TreePath selectedTreePath = jXTreeTable1.getPathForRow(selectedRow);
            if (!(selectedTreePath.getLastPathComponent() instanceof MyTreeNode))
                continue;

            MyTreeNode lastSelectedNode = (MyTreeNode)selectedTreePath.getLastPathComponent();
            if (!lastSelectedNode.getIsBusinessPartnerExternal())
            {
                printExternalOrderButton.setEnabled(false);
                break;
            }
        }
    }//GEN-LAST:event_jXTreeTable1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AllOrdersDialog dialog = new AllOrdersDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnDeleteOrder;
    private javax.swing.JButton _btnDeleteOrderItem;
    private javax.swing.JComboBox bpTypeFilterCBox;
    private javax.swing.JButton btnChangePosition;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton jButtonChaneQuantity;
    private javax.swing.JButton jButtonUpdateShippingDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTreeTable jXTreeTable1;
    private javax.swing.JButton printExternalOrderButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the treeTableModel
     */
    public MyTreeTableModel getTreeTableModel() {
        return treeTableModel;
    }

    /**
     * @param treeTableModel the treeTableModel to set
     */
    public void setTreeTableModel(MyTreeTableModel treeTableModel) {
        this.treeTableModel = treeTableModel;
    }


    public List<OrderType> getBpTypes() {
        return bpTypes;
    }

    public void setBpTypes(List<OrderType> bpTypes) {
        this.bpTypes = bpTypes;
    }
}
