/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllOrdersDialog.java
 *
 * Created on Feb 13, 2012, 7:12:35 PM
 */
package stefanpresentationlayer.dialogs;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;
import org.jdesktop.swingx.JXDatePicker;
import stefan.business.OrderManager;
import stefan.business.objects.Order;
import stefanpresentationlayer.MyTreeNode;
import stefanpresentationlayer.MyTreeTableModel;

/**
 *
 * @author Matija
 */
public class AllOrdersDialog extends javax.swing.JDialog {

   
    private MyTreeTableModel treeTableModel;
    /** Creates new form AllOrdersDialog */
    public AllOrdersDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);              
        initComponents(); 
        refreshTreeData();
        setTitle("Pregled Narudžbi");            
    }
  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTable1 = new org.jdesktop.swingx.JXTreeTable();
        closeBtn = new javax.swing.JButton();
        _btnDeleteOrder = new javax.swing.JButton();
        _btnDeleteOrderItem = new javax.swing.JButton();
        jButtonUpdateShippingDate = new javax.swing.JButton();
        jButtonChaneQuantity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(AllOrdersDialog.class);
        jXTreeTable1.setFont(resourceMap.getFont("jXTreeTable1.font")); // NOI18N
        jXTreeTable1.setName("jXTreeTable1"); // NOI18N
        jScrollPane1.setViewportView(jXTreeTable1);

        closeBtn.setText(resourceMap.getString("closeBtn.text")); // NOI18N
        closeBtn.setName("closeBtn"); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        _btnDeleteOrder.setText(resourceMap.getString("_btnDeleteOrder.text")); // NOI18N
        _btnDeleteOrder.setName("_btnDeleteOrder"); // NOI18N
        _btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDeleteOrderActionPerformed(evt);
            }
        });

        _btnDeleteOrderItem.setText(resourceMap.getString("_btnDeleteOrderItem.text")); // NOI18N
        _btnDeleteOrderItem.setName("_btnDeleteOrderItem"); // NOI18N
        _btnDeleteOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDeleteOrderItemActionPerformed(evt);
            }
        });

        jButtonUpdateShippingDate.setText(resourceMap.getString("jButtonUpdateShippingDate.text")); // NOI18N
        jButtonUpdateShippingDate.setName("jButtonUpdateShippingDate"); // NOI18N
        jButtonUpdateShippingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateShippingDateActionPerformed(evt);
            }
        });

        jButtonChaneQuantity.setText(resourceMap.getString("jButtonChaneQuantity.text")); // NOI18N
        jButtonChaneQuantity.setName("jButtonChaneQuantity"); // NOI18N
        jButtonChaneQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChaneQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_btnDeleteOrder)
                        .addGap(18, 18, 18)
                        .addComponent(_btnDeleteOrderItem)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateShippingDate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChaneQuantity))
                    .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnDeleteOrder)
                    .addComponent(_btnDeleteOrderItem)
                    .addComponent(jButtonUpdateShippingDate)
                    .addComponent(jButtonChaneQuantity))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void refreshTreeData(){
        OrderManager manager = new OrderManager();
        List<Order> items = manager.getOrders();
        treeTableModel = new MyTreeTableModel(items);   
        jXTreeTable1.setTreeTableModel(treeTableModel);
        jXTreeTable1.expandAll();
    }
    
    
    private void _btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDeleteOrderActionPerformed
        int row = jXTreeTable1.getSelectedRow();
        if (row!=-1)
        {            
            TreePath tp = jXTreeTable1.getPathForRow(row);
            MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
            OrderManager manager=new OrderManager();
            manager.deleteOrder(node.getOrderId());   
            
            refreshTreeData();
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite narudžbu.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event__btnDeleteOrderActionPerformed

    private void _btnDeleteOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDeleteOrderItemActionPerformed
        int row = jXTreeTable1.getSelectedRow();
        if (row!=-1)
        {
            TreePath tp = jXTreeTable1.getPathForRow(row);
            MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();            
            if (node.getOrderItemId()!=null)
            {
                OrderManager manager=new OrderManager();
                manager.deleteOrderItem(node.getOrderItemId());
                
                refreshTreeData();             
            }                    
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;        
        }        
    }//GEN-LAST:event__btnDeleteOrderItemActionPerformed

private void jButtonUpdateShippingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateShippingDateActionPerformed

    int row = jXTreeTable1.getSelectedRow();
    if (row != -1)
    {
        TreePath tp = jXTreeTable1.getPathForRow(row);
        MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
        if (node.getOrderItemId() != null)
        {            
            JXDatePicker jd = new JXDatePicker();
            jd.getMonthView().setPreferredColumnCount(2);
            jd.getMonthView().setPreferredRowCount(2);
            jd.getMonthView().setFirstDayOfWeek(2);
            jd.getMonthView().setShowingWeekNumber(true);  
            jd.getMonthView().getSelectionModel().setMinimalDaysInFirstWeek(4);
            jd.setFormats(new String[] {"d.M.yyyy."});            
            String message ="Odaberite novi datum isporuke:\n";
            Object[] params = {message,jd};
            JOptionPane.showConfirmDialog(null,params,"Datum Isporuke", JOptionPane.PLAIN_MESSAGE);
            Date newShippingDate = jd.getDate();
            if (newShippingDate == null)
            {
                return;
            }            
            
            OrderManager manager = new OrderManager();
            manager.UpdateOrderItemShippingDate(node.getOrderItemId(), newShippingDate);
                      
            refreshTreeData();    
        }
        else {
            JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
    }
    else {
        JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;        
    }
}//GEN-LAST:event_jButtonUpdateShippingDateActionPerformed

private void jButtonChaneQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChaneQuantityActionPerformed
    int row = jXTreeTable1.getSelectedRow();
    if (row != -1)
    {
        TreePath tp = jXTreeTable1.getPathForRow(row);
        MyTreeNode node = (MyTreeNode)tp.getLastPathComponent();
        if (node.getOrderItemId() != null)
        {
            boolean isAnswerOk = false;
            int parts = 0;
            
            while (!isAnswerOk) {
                String partsString = JOptionPane.showInputDialog(null, "Koliko komada?", "Broj komada", JOptionPane.QUESTION_MESSAGE);
                if (partsString == null) {                    
                    break;
                } else {
                   try {
                        parts = Integer.valueOf(partsString);
                        if (parts <= 0) {
                            JOptionPane.showMessageDialog(null, "Unesite više od 0 komada");
                        }
                        else {
                            isAnswerOk = true;                            
                        }                     
                   }
                   catch (NumberFormatException e) {
                       JOptionPane.showMessageDialog(null, "Unesite samo brojeve");
                   }
                }               
            }
            
            if (isAnswerOk){
                OrderManager manager = new OrderManager();
                manager.UpdateOrderItemQuantityOrdered(node.getOrderItemId(), parts);
            
                refreshTreeData();  
            }
        }
    }
    else {
        JOptionPane.showMessageDialog(null, "Odaberite stavku narudžbe.", "Upozorenje", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;        
    }

}//GEN-LAST:event_jButtonChaneQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllOrdersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AllOrdersDialog dialog = new AllOrdersDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnDeleteOrder;
    private javax.swing.JButton _btnDeleteOrderItem;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton jButtonChaneQuantity;
    private javax.swing.JButton jButtonUpdateShippingDate;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTreeTable jXTreeTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the treeTableModel
     */
    public MyTreeTableModel getTreeTableModel() {
        return treeTableModel;
    }

    /**
     * @param treeTableModel the treeTableModel to set
     */
    public void setTreeTableModel(MyTreeTableModel treeTableModel) {
        this.treeTableModel = treeTableModel;
    }

    
    
}
