/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditDesignJDialog.java
 *
 * Created on Feb 23, 2012, 7:29:57 PM
 */
package stefanpresentationlayer.dialogs;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import stefan.business.DesignManager;
import stefan.business.objects.Design;

/**
 *
 * @author Matija
 */
public class EditDesignJDialog extends javax.swing.JDialog {

    private Design design = new Design();
    private boolean isNew = false;

    /** Creates new form EditDesignJDialog */
    public EditDesignJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Upravljanje Nacrtima");
        panel.setVisible(false);
        btnSaveChanges.setEnabled(false);
        jPanel2.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        designNumberTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnFindDesign = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        price1000 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        price30 = new javax.swing.JTextField();
        price10 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        price100 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        revisionInput = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        price3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        price500 = new javax.swing.JTextField();
        price2 = new javax.swing.JTextField();
        price1 = new javax.swing.JTextField();
        designIdInput = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        designNumberInput = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        price200 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        percentTF = new javax.swing.JTextField();
        designClassInput = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        price4 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        price6 = new javax.swing.JTextField();
        price50 = new javax.swing.JTextField();
        price40 = new javax.swing.JTextField();
        price20 = new javax.swing.JTextField();
        price15 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        price5 = new javax.swing.JTextField();
        desigDateInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        neTokarenjeButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        daTokarenjeButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        neNiklanjeButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        daNiklanjeButton = new javax.swing.JRadioButton();
        designNameInput = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        createNewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(EditDesignJDialog.class);
        designNumberTF.setText(resourceMap.getString("designNumberTF.text")); // NOI18N
        designNumberTF.setName("designNumberTF"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        btnFindDesign.setText(resourceMap.getString("btnFindDesign.text")); // NOI18N
        btnFindDesign.setName("btnFindDesign"); // NOI18N
        btnFindDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDesignActionPerformed(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSaveChanges.setText(resourceMap.getString("btnSaveChanges.text")); // NOI18N
        btnSaveChanges.setName("btnSaveChanges"); // NOI18N
        btnSaveChanges.setNextFocusableComponent(btnCancel);
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setName("panel"); // NOI18N

        price1000.setName("price1000"); // NOI18N
        price1000.setNextFocusableComponent(daTokarenjeButton);

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        price30.setName("price30"); // NOI18N
        price30.setNextFocusableComponent(price40);

        price10.setName("price10"); // NOI18N
        price10.setNextFocusableComponent(price15);

        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N

        price100.setName("price100"); // NOI18N
        price100.setNextFocusableComponent(price200);

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        revisionInput.setName("revisionInput"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N

        price3.setName("price3"); // NOI18N
        price3.setNextFocusableComponent(price4);

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel36.setText(resourceMap.getString("jLabel36.text")); // NOI18N
        jLabel36.setName("jLabel36"); // NOI18N

        price500.setName("price500"); // NOI18N
        price500.setNextFocusableComponent(price1000);

        price2.setName("price2"); // NOI18N
        price2.setNextFocusableComponent(price3);

        price1.setName("price1"); // NOI18N
        price1.setNextFocusableComponent(price2);

        designIdInput.setName("designIdInput"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        designNumberInput.setEditable(false);
        designNumberInput.setName("designNumberInput"); // NOI18N

        jLabel35.setText(resourceMap.getString("jLabel35.text")); // NOI18N
        jLabel35.setName("jLabel35"); // NOI18N

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N

        price200.setName("price200"); // NOI18N
        price200.setNextFocusableComponent(price500);

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        percentTF.setName("percentTF"); // NOI18N

        designClassInput.setName("designClassInput"); // NOI18N

        jLabel37.setText(resourceMap.getString("jLabel37.text")); // NOI18N
        jLabel37.setName("jLabel37"); // NOI18N

        price4.setName("price4"); // NOI18N
        price4.setNextFocusableComponent(price5);

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N

        price6.setName("price6"); // NOI18N
        price6.setNextFocusableComponent(price10);

        price50.setName("price50"); // NOI18N
        price50.setNextFocusableComponent(price100);

        price40.setName("price40"); // NOI18N
        price40.setNextFocusableComponent(price50);

        price20.setName("price20"); // NOI18N
        price20.setNextFocusableComponent(price30);

        price15.setName("price15"); // NOI18N
        price15.setNextFocusableComponent(price20);

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        price5.setName("price5"); // NOI18N
        price5.setNextFocusableComponent(price6);

        desigDateInput.setEditable(false);
        desigDateInput.setText(resourceMap.getString("desigDateInput.text")); // NOI18N
        desigDateInput.setName("desigDateInput"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        buttonGroup2.add(neTokarenjeButton);
        neTokarenjeButton.setText(resourceMap.getString("neTokarenjeButton.text")); // NOI18N
        neTokarenjeButton.setName("neTokarenjeButton"); // NOI18N
        neTokarenjeButton.setNextFocusableComponent(daNiklanjeButton);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(resourceMap.getString("jLabel2.toolTipText")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        buttonGroup2.add(daTokarenjeButton);
        daTokarenjeButton.setText(resourceMap.getString("daTokarenjeButton.text")); // NOI18N
        daTokarenjeButton.setName("daTokarenjeButton"); // NOI18N
        daTokarenjeButton.setNextFocusableComponent(neTokarenjeButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(daTokarenjeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(neTokarenjeButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neTokarenjeButton)
                    .addComponent(daTokarenjeButton))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel2.AccessibleContext.accessibleName")); // NOI18N
        jLabel2.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jLabel2.AccessibleContext.accessibleDescription")); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        buttonGroup1.add(neNiklanjeButton);
        neNiklanjeButton.setText(resourceMap.getString("neNiklanjeButton.text")); // NOI18N
        neNiklanjeButton.setName("neNiklanjeButton"); // NOI18N
        neNiklanjeButton.setNextFocusableComponent(btnSaveChanges);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        buttonGroup1.add(daNiklanjeButton);
        daNiklanjeButton.setText(resourceMap.getString("daNiklanjeButton.text")); // NOI18N
        daNiklanjeButton.setName("daNiklanjeButton"); // NOI18N
        daNiklanjeButton.setNextFocusableComponent(neNiklanjeButton);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(daNiklanjeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(neNiklanjeButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neNiklanjeButton)
                    .addComponent(daNiklanjeButton))
                .addContainerGap())
        );

        designNameInput.setName("designNameInput"); // NOI18N

        jLabel38.setText(resourceMap.getString("jLabel38.text")); // NOI18N
        jLabel38.setName("jLabel38"); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(designNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revisionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price15))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price10))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price6))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price5))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price4))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price3))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price2))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(designIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price30, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price500, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price1000, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price40, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price50, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price100, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price200, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(percentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designClassInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desigDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(272, 272, 272))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel38)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revisionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designClassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desigDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(price20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel37))
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(price30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(price40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(price100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(price10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(price500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(price15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(price1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jLabel38.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel38.AccessibleContext.accessibleName")); // NOI18N

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 840, -1));

        createNewButton.setText(resourceMap.getString("createNewButton.text")); // NOI18N
        createNewButton.setName("createNewButton"); // NOI18N
        createNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(designNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFindDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createNewButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaveChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(designNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindDesign)
                    .addComponent(createNewButton))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDesignActionPerformed
        DesignManager manager = new DesignManager();
        List<Design> designs = manager.GetDesignsByNumber(designNumberTF.getText());
        LoadData(designs);

    }//GEN-LAST:event_btnFindDesignActionPerformed

    public void LoadData(List<Design> designs) {
        if (designs.size() == 1) {
            btnSaveChanges.setEnabled(true);
            panel.setVisible(true);
            design = designs.get(0);
            designClassInput.setText(design.getClassMark());
            designIdInput.setText(design.getDesignIdentity());
            designNameInput.setText(design.getName());
            designNumberInput.setText(design.getDesignNumber());
            revisionInput.setText(design.getRevision());
            SimpleDateFormat f = new SimpleDateFormat("dd.MM.yyyy");
            desigDateInput.setText(f.format(design.getDate()));

            if (design.isNiklanje())
            {
                daNiklanjeButton.setSelected(true);
            }
            else
            {
                neNiklanjeButton.setSelected(true);
            }
            
            if (design.getIsTokarenje())
            {
                daTokarenjeButton.setSelected(true);
            }
            else
            {
                neTokarenjeButton.setSelected(true);
            }
            
            if (design.getPcs1() != null) {
                price1.setText(design.getPcs1().toPlainString().replace('.', ','));
            } else {
                price1.setText("");
            }
            if (design.getPcs2() != null) {
                price2.setText(design.getPcs2().toPlainString().replace('.', ','));
            } else {
                price2.setText("");
            }
            if (design.getPcs3() != null) {
                price3.setText(design.getPcs3().toPlainString().replace('.', ','));
            } else {
                price3.setText("");
            }
            if (design.getPcs4() != null) {
                price4.setText(design.getPcs4().toPlainString().replace('.', ','));
            } else {
                price4.setText("");
            }
            if (design.getPcs5() != null) {
                price5.setText(design.getPcs5().toPlainString().replace('.', ','));
            } else {
                price5.setText("");
            }
            if (design.getPcs6() != null) {
                price6.setText(design.getPcs6().toPlainString().replace('.', ','));
            } else {
                price6.setText("");
            }
            if (design.getPcs10() != null) {
                price10.setText(design.getPcs10().toPlainString().replace('.', ','));
            } else {
                price10.setText("");
            }
            if (design.getPcs15() != null) {
                price15.setText(design.getPcs15().toPlainString().replace('.', ','));
            } else {
                price15.setText("");
            }
            if (design.getPcs20() != null) {
                price20.setText(design.getPcs20().toPlainString().replace('.', ','));
            } else {
                price20.setText("");
            }
            if (design.getPcs30() != null) {
                price30.setText(design.getPcs30().toPlainString().replace('.', ','));
            } else {
                price30.setText("");
            }
            if (design.getPcs40() != null) {
                price40.setText(design.getPcs40().toPlainString().replace('.', ','));
            } else {
                price40.setText("");
            }

            if (design.getPcs50() != null) {
                price50.setText(design.getPcs50().toPlainString().replace('.', ','));
            } else {
                price50.setText("");
            }
            if (design.getPcs100() != null) {
                price100.setText(design.getPcs100().toPlainString().replace('.', ','));
            } else {
                price100.setText("");
            }
            if (design.getPcs200() != null) {
                price200.setText(design.getPcs200().toPlainString().replace('.', ','));
            } else {
                price200.setText("");
            }
            if (design.getPcs500() != null) {
                price500.setText(design.getPcs500().toPlainString().replace('.', ','));
            } else {
                price500.setText("");
            }
            if (design.getPcs1000() != null) {
                price1000.setText(design.getPcs1000().toPlainString().replace('.', ','));
            } else {
                price1000.setText("");
            }


        } else {
            panel.setVisible(false);
            btnSaveChanges.setEnabled(false);
        }

    }

    public void CreateNew() {
        jPanel2.setVisible(true);
        neNiklanjeButton.setSelected(true);
        daTokarenjeButton.setSelected(true);
        btnSaveChanges.setEnabled(true);
        panel.setVisible(true);
        SimpleDateFormat f = new SimpleDateFormat("dd.MM.yyyy");
        desigDateInput.setText(f.format(new Date()));
        designNumberInput.setEditable(true);
        btnFindDesign.setEnabled(false);
        isNew = true;
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BigDecimal percent;
        try {
            percent = new BigDecimal(percentTF.getText().replace(',', '.'));
            percent = percent.divide(new BigDecimal("100"), 2, RoundingMode.HALF_UP);
            percent = percent.add(BigDecimal.ONE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Unesite samo brojeve");
            return;
        }


        try {
            BigDecimal price = new BigDecimal(price1.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price1.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price2.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price2.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price3.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price3.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price4.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price4.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price5.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price5.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price6.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price6.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price10.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price10.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price15.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price15.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price20.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price20.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price30.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price30.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price40.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price40.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price50.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price50.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price100.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price100.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price200.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price200.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price500.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price500.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }
        try {
            BigDecimal price = new BigDecimal(price1000.getText().replace(',', '.'));
            price = price.multiply(percent).setScale(2, RoundingMode.HALF_UP);
            price1000.setText(price.toPlainString().replace('.', ','));
        } catch (NumberFormatException e) {
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        boolean priceChanged = false;
        if (isNew) {
            design = new stefan.business.objects.Design();
            design.setDesignNumber(designNumberInput.getText());
            design.setDate(new Date());

        }
        try {
            if (!isNew && design.getPcs1()==null && (price1.getText()!= null || !"".equals(price1.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs1()!=null && design.getPcs1().compareTo(new BigDecimal(price1.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }

            design.setPcs1(new BigDecimal(price1.getText().replace(',', '.')));

        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs2()==null && (price2.getText()!= null || !"".equals(price2.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs2()!=null && design.getPcs2().compareTo(new BigDecimal(price2.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs2(new BigDecimal(price2.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs3()==null && (price3.getText()!= null || !"".equals(price3.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs3()!=null && design.getPcs3().compareTo(new BigDecimal(price3.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs3(new BigDecimal(price3.getText().replace(',', '.')));

        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs4()==null && (price4.getText()!= null || !"".equals(price4.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs4()!=null && design.getPcs4().compareTo(new BigDecimal(price4.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs4(new BigDecimal(price4.getText().replace(',', '.')));

        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs5()==null && (price5.getText()!= null || !"".equals(price5.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs5()!=null && design.getPcs5().compareTo(new BigDecimal(price5.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs5(new BigDecimal(price5.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try { 
            if (!isNew && design.getPcs6()==null && (price6.getText()!= null || !"".equals(price6.getText()))) {
                priceChanged = true;
            }
            if (!isNew &&  design.getPcs6()!=null && design.getPcs6().compareTo(new BigDecimal(price6.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs6(new BigDecimal(price6.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs10()==null && (price10.getText()!= null || !"".equals(price10.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs10()!=null && design.getPcs10().compareTo(new BigDecimal(price10.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs10(new BigDecimal(price10.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs15()==null && (price15.getText()!= null || !"".equals(price15.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs15()!=null && design.getPcs15().compareTo(new BigDecimal(price15.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs15(new BigDecimal(price15.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs20()==null && (price20.getText()!= null || !"".equals(price20.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs20()!=null && design.getPcs20().compareTo(new BigDecimal(price20.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs20(new BigDecimal(price20.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs30()==null && (price30.getText()!= null || !"".equals(price30.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs30()!=null && design.getPcs30().compareTo(new BigDecimal(price30.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs30(new BigDecimal(price30.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs40()==null && (price40.getText()!= null || !"".equals(price40.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs40()!=null && design.getPcs40().compareTo(new BigDecimal(price40.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs40(new BigDecimal(price40.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs50()==null && (price50.getText()!= null || !"".equals(price50.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs50()!=null && design.getPcs50().compareTo(new BigDecimal(price50.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs50(new BigDecimal(price50.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs100()==null && (price100.getText()!= null || !"".equals(price100.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs100()!=null && design.getPcs100().compareTo(new BigDecimal(price100.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs100(new BigDecimal(price100.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs200()==null && (price200.getText()!= null || !"".equals(price200.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs200()!=null && design.getPcs200().compareTo(new BigDecimal(price200.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs200(new BigDecimal(price200.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs500()==null && (price500.getText()!= null || !"".equals(price500.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs500()!=null && design.getPcs500().compareTo(new BigDecimal(price500.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs500(new BigDecimal(price500.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }
        try {
            if (!isNew && design.getPcs1000()==null && (price1000.getText()!= null || !"".equals(price1000.getText()))) {
                priceChanged = true;
            }
            if (!isNew && design.getPcs1000()!=null && design.getPcs1000().compareTo(new BigDecimal(price1000.getText().replace(',', '.'))) != 0) {
                priceChanged = true;
            }
            design.setPcs1000(new BigDecimal(price1000.getText().replace(',', '.')));
        } catch (NumberFormatException e) {
        }

        if (priceChanged) {
            design.setDate(new Date());
        }
        
        if(daNiklanjeButton.isSelected()) {
            design.setNiklanje(true);
        }
            else {
            design.setNiklanje(false);
        }
        
        if(daTokarenjeButton.isSelected()) {
            design.setIsTokarenje(true);
        }
            else {
            design.setIsTokarenje(false);
        }
        
        design.setName(designNameInput.getText());
        design.setClassMark(designClassInput.getText());
        design.setDesignIdentity(designIdInput.getText());
        design.setRevision(revisionInput.getText());
        DesignManager manager = new DesignManager();
        try {
            if (!isNew) {
                manager.ChangeDesign(design);
            } else {
                manager.SaveDesign(design);
            }
        } catch (Exception ex) {
            Logger.getLogger(EditDesignJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();

    }//GEN-LAST:event_btnSaveChangesActionPerformed
     
private void createNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewButtonActionPerformed
   CreateNew();
}//GEN-LAST:event_createNewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDesignJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditDesignJDialog dialog = new EditDesignJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFindDesign;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createNewButton;
    private javax.swing.JRadioButton daNiklanjeButton;
    private javax.swing.JRadioButton daTokarenjeButton;
    private javax.swing.JTextField desigDateInput;
    private javax.swing.JTextField designClassInput;
    private javax.swing.JTextField designIdInput;
    private javax.swing.JTextField designNameInput;
    private javax.swing.JTextField designNumberInput;
    private javax.swing.JTextField designNumberTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton neNiklanjeButton;
    private javax.swing.JRadioButton neTokarenjeButton;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField percentTF;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField price10;
    private javax.swing.JTextField price100;
    private javax.swing.JTextField price1000;
    private javax.swing.JTextField price15;
    private javax.swing.JTextField price2;
    private javax.swing.JTextField price20;
    private javax.swing.JTextField price200;
    private javax.swing.JTextField price3;
    private javax.swing.JTextField price30;
    private javax.swing.JTextField price4;
    private javax.swing.JTextField price40;
    private javax.swing.JTextField price5;
    private javax.swing.JTextField price50;
    private javax.swing.JTextField price500;
    private javax.swing.JTextField price6;
    private javax.swing.JTextField revisionInput;
    // End of variables declaration//GEN-END:variables
}
