/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaterialManagmentJDialog.java
 *
 * Created on 09.02.2012., 16:27:38
 */
package stefanpresentationlayer.dialogs;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.jdesktop.application.Action;
import stefan.business.MaterialManager;
import stefan.business.objects.MaterialDetails;

/**
 *
 * @author Robert
 */
public class MaterialManagmentJDialog extends javax.swing.JDialog {

    private List<MaterialDetails> details = new ArrayList<MaterialDetails>();

    /** Creates new form MaterialManagmentJDialog */
    public MaterialManagmentJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Upravljanje Materijalima");
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        RefreshMaterialTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addMaterialBtn = new javax.swing.JButton();
        editMaterialBtn = new javax.swing.JButton();
        deleteMaterialBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${details}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${materialName}"));
        columnBinding.setColumnName("Material Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${density}"));
        columnBinding.setColumnName("Density");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${niklanje}"));
        columnBinding.setColumnName("Niklanje");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(MaterialManagmentJDialog.class);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getActionMap(MaterialManagmentJDialog.class, this);
        addMaterialBtn.setAction(actionMap.get("addNewMaterial")); // NOI18N
        addMaterialBtn.setIcon(resourceMap.getIcon("addMaterialBtn.icon")); // NOI18N
        addMaterialBtn.setText(resourceMap.getString("addMaterialBtn.text")); // NOI18N
        addMaterialBtn.setToolTipText(resourceMap.getString("addMaterialBtn.toolTipText")); // NOI18N
        addMaterialBtn.setName("addMaterialBtn"); // NOI18N

        editMaterialBtn.setAction(actionMap.get("editMaterialBtnClicked")); // NOI18N
        editMaterialBtn.setIcon(resourceMap.getIcon("editMaterialBtn.icon")); // NOI18N
        editMaterialBtn.setText(resourceMap.getString("editMaterialBtn.text")); // NOI18N
        editMaterialBtn.setToolTipText(resourceMap.getString("editMaterialBtn.toolTipText")); // NOI18N
        editMaterialBtn.setName("editMaterialBtn"); // NOI18N

        deleteMaterialBtn.setAction(actionMap.get("deleteMaterialBtnClicked")); // NOI18N
        deleteMaterialBtn.setIcon(resourceMap.getIcon("deleteMaterialBtn.icon")); // NOI18N
        deleteMaterialBtn.setText(resourceMap.getString("deleteMaterialBtn.text")); // NOI18N
        deleteMaterialBtn.setToolTipText(resourceMap.getString("deleteMaterialBtn.toolTipText")); // NOI18N
        deleteMaterialBtn.setName("deleteMaterialBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMaterialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        int keyCode = evt.getKeyCode();
        if(keyCode == KeyEvent.VK_DELETE){
            evt.consume();
            deleteMaterialBtnClicked();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterialManagmentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterialManagmentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterialManagmentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialManagmentJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MaterialManagmentJDialog dialog = new MaterialManagmentJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void addNewMaterial() {
        NewMaterialJDialog newMaterialJDialog = new NewMaterialJDialog(null, true);
        newMaterialJDialog.setResizable(false);  
        newMaterialJDialog.setLocation(0, 50);
        newMaterialJDialog.setVisible(true);
        RefreshMaterialTable();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMaterialBtn;
    private javax.swing.JButton deleteMaterialBtn;
    private javax.swing.JButton editMaterialBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void RefreshMaterialTable() {
        MaterialManager manager = new MaterialManager();
        details = manager.GetAllMaterialDetails();
        this.firePropertyChange("details", null, null);
    }

    /**
     * @return the details
     */
    public List<MaterialDetails> getDetails() {
        return details;
    }

    /**
     * @param details the details to set
     */
    public void setDetails(List<MaterialDetails> details) {
        this.details = details;
    }

    @Action
    public void deleteMaterialBtnClicked() {
        int selectedIndex = jTable1.getSelectedRow();
        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(null, "Odaberite materijal","Greška",JOptionPane.ERROR_MESSAGE);
        }else{
            int materialId = details.get(selectedIndex).getIdMaterialDetails();
            MaterialManager manager = new MaterialManager();
            try {
                manager.DeleteMaterialDetails(materialId);
                RefreshMaterialTable();
            } catch (Exception e) {
                            
                JOptionPane.showMessageDialog(null,e.toString(),"Greška",JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    @Action
    public void editMaterialBtnClicked() {
        int selectedIndex = jTable1.getSelectedRow();
        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(null, "Odaberite materijal","Greška",JOptionPane.ERROR_MESSAGE);
        }else{
            int materialId = details.get(selectedIndex).getIdMaterialDetails();
            EditeMaterialJDialog editDialog = new EditeMaterialJDialog(null, true, materialId);
            editDialog.setResizable(false);
            editDialog.setLocation(0, 50);
            editDialog.setVisible(true);
            RefreshMaterialTable();
        }
    }
}
