/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewExternalBusinessPartnerJDialog.java
 *
 * Created on 19-May-2026, 00:24:42
 */
package stefanpresentationlayer.dialogs;

import org.jdesktop.observablecollections.ObservableCollections;
import stefan.business.BusinessPartnerManager;
import stefan.business.objects.BusinessPartner;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Luka
 */
public class NewExternalBusinessPartnerJDialog extends javax.swing.JDialog {
    private List<BusinessPartner> externalBusinessPartners = ObservableCollections.observableList(new ArrayList<BusinessPartner>());

    /** Creates new form NewExternalBusinessPartnerJDialog */
    public NewExternalBusinessPartnerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        BusinessPartnerManager bpm = new BusinessPartnerManager();
        externalBusinessPartners.addAll(bpm.getExternalBusinessPartners());
    }

    public List<BusinessPartner> getExternalBusinessPartners() {
        return externalBusinessPartners;
    }

    public void setExternalBusinessPartners(List<BusinessPartner> externalBusinessPartners) {
        this.externalBusinessPartners = externalBusinessPartners;
    }

    private BusinessPartner selectedPartnerForEdit;

    public BusinessPartner getSelectedPartnerForEdit() {
        return selectedPartnerForEdit;
    }

    private void fillEditFields() {
        this.name.setText(this.selectedPartnerForEdit.getName());
        this.displayName.setText(this.selectedPartnerForEdit.getDisplayName());
        this.printRow1.setText(this.selectedPartnerForEdit.getPrintRow1());
        this.printRow2.setText(this.selectedPartnerForEdit.getPrintRow2());
        this.city.setText(this.selectedPartnerForEdit.getCity());
        this.printRow3.setText(this.selectedPartnerForEdit.getPrintRow3());
    }

    private void selectBussPartnerForEdit(BusinessPartner bp) {
        this.selectedPartnerForEdit = new BusinessPartner();

        this.selectedPartnerForEdit.setIsExternalSource(true);
        this.selectedPartnerForEdit.setPrintInd(false);
        this.selectedPartnerForEdit.setRequireShippingDate(false);

        if (bp == null) {
            this.cancelEditBtn.setEnabled(false);
            this.deleteSupplierBtn.setEnabled(false);
            fillEditFields();
            return;
        }

        this.selectedPartnerForEdit.setId(bp.getId());

        this.selectedPartnerForEdit.setName(bp.getName());
        this.selectedPartnerForEdit.setDisplayName(bp.getDisplayName());
        this.selectedPartnerForEdit.setPrintRow1(bp.getPrintRow1());
        this.selectedPartnerForEdit.setPrintRow2(bp.getPrintRow2());
        this.selectedPartnerForEdit.setCity(bp.getCity());
        this.selectedPartnerForEdit.setPrintRow3(bp.getPrintRow3());


        this.cancelEditBtn.setEnabled(true);
        this.deleteSupplierBtn.setEnabled(true);

        fillEditFields();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        displayName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        printRow1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        printRow2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        printRow3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        cancelEditBtn = new javax.swing.JButton();
        deleteSupplierBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        externalSuppliersTab = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova vanjska firma"); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(NewExternalBusinessPartnerJDialog.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        name.setToolTipText(resourceMap.getString("name.toolTipText")); // NOI18N
        name.setName("name"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        displayName.setName("displayName"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        printRow1.setName("printRow1"); // NOI18N
        printRow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRow1ActionPerformed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        printRow2.setName("printRow2"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setToolTipText(resourceMap.getString("jLabel6.toolTipText")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        printRow3.setName("printRow3"); // NOI18N
        printRow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRow3ActionPerformed(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        city.setToolTipText(resourceMap.getString("city.toolTipText")); // NOI18N
        city.setName("city"); // NOI18N

        confirmButton.setText(resourceMap.getString("confirmButton.text")); // NOI18N
        confirmButton.setToolTipText(resourceMap.getString("confirmButton.toolTipText")); // NOI18N
        confirmButton.setName("confirmButton"); // NOI18N
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelBtn.setText(resourceMap.getString("cancelBtn.text")); // NOI18N
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        cancelEditBtn.setText(resourceMap.getString("cancelEditBtn.text")); // NOI18N
        cancelEditBtn.setEnabled(false);
        cancelEditBtn.setName("cancelEditBtn"); // NOI18N
        cancelEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditBtnActionPerformed(evt);
            }
        });

        deleteSupplierBtn.setText(resourceMap.getString("deleteSupplierBtn.text")); // NOI18N
        deleteSupplierBtn.setEnabled(false);
        deleteSupplierBtn.setName("deleteSupplierBtn"); // NOI18N
        deleteSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelEditBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteSupplierBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(printRow1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(displayName, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(printRow2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(printRow3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printRow3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelBtn)
                    .addComponent(cancelEditBtn)
                    .addComponent(deleteSupplierBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(801, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jPanel3.border.lineColor"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        externalSuppliersTab.setName("externalSuppliersTab"); // NOI18N
        externalSuppliersTab.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${externalBusinessPartners}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, externalSuppliersTab);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${displayName}"));
        columnBinding.setColumnName("Display Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${city}"));
        columnBinding.setColumnName("City");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${printRow3}"));
        columnBinding.setColumnName("Print Row3");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        externalSuppliersTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                externalSuppliersTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(externalSuppliersTab);
        externalSuppliersTab.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("externalSuppliersTab.columnModel.title0")); // NOI18N
        externalSuppliersTab.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("externalSuppliersTab.columnModel.title1")); // NOI18N
        externalSuppliersTab.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("externalSuppliersTab.columnModel.title2")); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void printRow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRow1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_printRow1ActionPerformed

private void printRow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRow3ActionPerformed

}//GEN-LAST:event_printRow3ActionPerformed

    private static boolean isStringNullOrEmpty(String str) {
        return str == null || str.isEmpty();
    }
private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
    StringBuilder validationMessageBuilder = new StringBuilder();

    String name = this.name.getText();
    if (isStringNullOrEmpty(name)) {
        validationMessageBuilder.append("Polje 'Naziv' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String displayName = this.displayName.getText();
    if (isStringNullOrEmpty(displayName)) {
        validationMessageBuilder.append("Polje 'Kratki naziv' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String printRow1 = this.printRow1.getText();
    if (isStringNullOrEmpty(printRow1)) {
        validationMessageBuilder.append("Polje 'Adresa' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String printRow2 = this.printRow2.getText();
    if (isStringNullOrEmpty(printRow2)) {
        validationMessageBuilder.append("Polje 'Adresa' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String printRow3 = this.printRow3.getText();
    if (isStringNullOrEmpty(printRow3)) {
        validationMessageBuilder.append("Polje 'PDV ID. BR.' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String city = this.city.getText();
    if (isStringNullOrEmpty(city)) {
        validationMessageBuilder.append("Polje 'Grad' mora biti popunjeno");
        validationMessageBuilder.append('\n');
    }

    String validationMessage = validationMessageBuilder.toString();
    if (!isStringNullOrEmpty(validationMessage)) {
        JOptionPane.showMessageDialog(null, validationMessage, "Provjerite unesene vrijednosti", JOptionPane.WARNING_MESSAGE);
        return;
    }

    BusinessPartnerManager bpm = new BusinessPartnerManager();
    BusinessPartner newBp = new BusinessPartner();

    if (this.selectedPartnerForEdit != null && this.selectedPartnerForEdit.getId() != null) {
        newBp.setId(this.selectedPartnerForEdit.getId());
    }

    newBp.setName(name);
    newBp.setDisplayName(displayName);
    newBp.setPrintInd(false);
    newBp.setPrintRow1(printRow1);
    newBp.setPrintRow2(printRow2);
    newBp.setPrintRow3(printRow3);
    newBp.setCity(city);
    newBp.setRequireShippingDate(false);
    newBp.setIsExternalSource(true);

    bpm.saveBusinessPartner(newBp);
    this.dispose();
}//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void externalSuppliersTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalSuppliersTabMouseClicked
        if (evt.getClickCount() < 2)
            return;

        int row = this.externalSuppliersTab.getSelectedRow();
        if (row < 0 || row >= this.externalBusinessPartners.size())
            return;

        this.selectBussPartnerForEdit(this.externalBusinessPartners.get(row));
    }//GEN-LAST:event_externalSuppliersTabMouseClicked

    private void cancelEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditBtnActionPerformed
        this.selectBussPartnerForEdit(null);
    }//GEN-LAST:event_cancelEditBtnActionPerformed

    private void deleteSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierBtnActionPerformed
        Object[] opts = new Object[] { "Da", "Ne" };
        int res = JOptionPane.showOptionDialog(
            null,
            "Jeste li sigurni da želite ukloniti odabranog dobavljača?",
            "Brisanje dobavljača",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opts,
            opts[1]
        );

        if (res == JOptionPane.CLOSED_OPTION || res == 1)
            return;

        int row = this.externalSuppliersTab.getSelectedRow();
        if (row < 0 || row >= this.externalBusinessPartners.size())
            return;

        BusinessPartner bp = this.externalBusinessPartners.get(row);
        if (bp.getId() == null || bp.getId() == 0)
            return;

        BusinessPartnerManager bpm = new BusinessPartnerManager();
        bpm.deleteExternalBusinessPartner(bp);
        this.externalBusinessPartners.remove(row);
        this.selectBussPartnerForEdit(null);
    }//GEN-LAST:event_deleteSupplierBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewExternalBusinessPartnerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewExternalBusinessPartnerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewExternalBusinessPartnerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewExternalBusinessPartnerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewExternalBusinessPartnerJDialog dialog = new NewExternalBusinessPartnerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelEditBtn;
    private javax.swing.JTextField city;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteSupplierBtn;
    private javax.swing.JTextField displayName;
    private javax.swing.JTable externalSuppliersTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField printRow1;
    private javax.swing.JTextField printRow2;
    private javax.swing.JTextField printRow3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
