/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewExternalOrderItemJDialog.java
 *
 * Created on 28-May-2026, 21:56:42
 */
package stefanpresentationlayer.dialogs;

import stefan.business.PresentationHelper;
import stefan.business.objects.Design;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Luka
 */
public class NewExternalOrderItemJDialog extends javax.swing.JDialog {

    /** Creates new form NewExternalOrderItemJDialog */
    public NewExternalOrderItemJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private Design design;

    private void setDesignCalcParameters() {
        final String decimalFormat = "%.2f";

        fertigCBox.setSelected(design.getCalcIsFerting());

        if (design.getCalcMinPoKom() != null)
            minPerPiece.setText(String.format(decimalFormat, design.getCalcMinPoKom().doubleValue()));
        else
            minPerPiece.setText("<neodr.>");

        if (design.getCalcStezanjeTok() != null)
            tightLathing.setText(String.format(decimalFormat, design.getCalcStezanjeTok().doubleValue()));
        else
            tightLathing.setText("<neodr.>");

        if (design.getCalcStezanjeGlod() != null)
            tightMilling.setText(String.format(decimalFormat, design.getCalcStezanjeGlod().doubleValue()));
        else
            tightMilling.setText("<neodr.>");

        if (design.getCalcSatnica() != null)
            hourlyCost.setText(String.format(decimalFormat, design.getCalcSatnica().doubleValue()));
        else
            hourlyCost.setText("<neodr.>");

        if (design.getCalcEurPoKom() != null)
            pricePerPiece.setText(String.format(decimalFormat, design.getCalcEurPoKom().doubleValue()));
        else
            pricePerPiece.setText("<neodr.>");
    }

    private void initDesignPricingTable() {
        pricingTable.setModel(new DefaultTableModel() {
            private Design design;
            private List<Integer> cachedQuantities;

            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public String getColumnName(int column) {
                if (column == 0)
                    return "Količina";

                if (column == 1)
                    return "Cijena";

                return "Unknown";
            }

            @Override
            public int getRowCount() {
                if (this.design == null)
                    this.design = NewExternalOrderItemJDialog.this.design;

                if (this.cachedQuantities == null)
                    this.cachedQuantities = this.design.getSetPcsQuantities();

                return this.cachedQuantities.size();
            }

            @Override
            public Object getValueAt(int row, int column) {
                if (this.design == null)
                    this.design = NewExternalOrderItemJDialog.this.design;

                if (this.cachedQuantities == null)
                    this.cachedQuantities = this.design.getSetPcsQuantities();

                if (this.cachedQuantities.size() <= row)
                    throw new RuntimeException("Illegal row count");

                int qty = this.cachedQuantities.get(row);
                if (column == 0) {
                    return Integer.toString(qty);
                }

                if (column != 1)
                    return "Unknown";

                return String.format("%.2f", this.design.getPriceForPcs(qty).doubleValue());
            }
        });
    }

    public NewExternalOrderItemJDialog(java.awt.Frame parent, boolean modal, Design design) {
        this(parent, modal);

        this.design = design;

        setDesignCalcParameters();
        initDesignPricingTable();
    }

    private int optionPaneExitCode = JOptionPane.CANCEL_OPTION;
    public boolean isOkExitStatus() {
        return this.optionPaneExitCode == JOptionPane.OK_OPTION;
    }

    private int quantityValue;
    public int getQuantity() {
        return this.quantityValue;
    }

    private double finalPriceValue;
    public double getFinalPriceValue() {
        return finalPriceValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fertigCBox = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        minPerPiece = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tightLathing = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tightMilling = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hourlyCost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pricePerPiece = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pricingTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        quantity = new javax.swing.JTextField();
        finalPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 500));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 204));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 16, 0));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(NewExternalOrderItemJDialog.class);
        fertigCBox.setText(resourceMap.getString("fertigCBox.text")); // NOI18N
        fertigCBox.setEnabled(false);
        fertigCBox.setName("fertigCBox"); // NOI18N
        jPanel4.add(fertigCBox);

        jPanel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        minPerPiece.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        minPerPiece.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        minPerPiece.setName("minPerPiece"); // NOI18N
        minPerPiece.setPreferredSize(new java.awt.Dimension(200, 14));
        jPanel4.add(minPerPiece);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel4.add(jLabel1);

        tightLathing.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tightLathing.setName("tightLathing"); // NOI18N
        jPanel4.add(tightLathing);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel4.add(jLabel2);

        tightMilling.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tightMilling.setName("tightMilling"); // NOI18N
        jPanel4.add(tightMilling);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel4.add(jLabel3);

        hourlyCost.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hourlyCost.setName("hourlyCost"); // NOI18N
        jPanel4.add(hourlyCost);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel4.add(jLabel4);

        pricePerPiece.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pricePerPiece.setName("pricePerPiece"); // NOI18N
        jPanel4.add(pricePerPiece);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel4.add(jLabel5);

        jPanel1.add(jPanel4);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pricingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pricingTable.setName("pricingTable"); // NOI18N
        jScrollPane1.setViewportView(pricingTable);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setName("jPanel2"); // NOI18N

        quantity.setName("quantity"); // NOI18N
        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });

        finalPrice.setName("finalPrice"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        confirmBtn.setText(resourceMap.getString("confirmBtn.text")); // NOI18N
        confirmBtn.setName("confirmBtn"); // NOI18N
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText(resourceMap.getString("cancelBtn.text")); // NOI18N
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(finalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(confirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)
                        .addGap(7, 7, 7))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(finalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
        int qtyValue;

        try {
            qtyValue = Integer.parseInt(quantity.getText());
        } catch (NumberFormatException nfe) {
            return;
        }

        if (qtyValue <= 0) {
            JOptionPane.showMessageDialog(this.getParent(), "Upišite ispravnu vrijednost za količinu (vrijednost mora biti veća od 0)", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PresentationHelper ph = new PresentationHelper(this.design, qtyValue, null);
        this.finalPrice.setText(ph.getPricePerPart().toString());
    }//GEN-LAST:event_quantityFocusLost

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.optionPaneExitCode = JOptionPane.CANCEL_OPTION;
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        String errorMessage = null;

        String quantityText = quantity.getText();
        if (quantityText == null || quantityText.isEmpty())
            errorMessage = "Količina je obavezan podatak";

        String finalPriceText = finalPrice.getText();
        if (finalPriceText == null || finalPriceText.isEmpty()) {
            String msg = "Konačna cijena je obavezan podatak";
            if (errorMessage != null)
                errorMessage += "\n" + msg;
            else
                errorMessage = msg;
        }

        if (errorMessage == null) {
            String msg = "Količina mora biti cijeli broj veći od 0";
            try {
                quantityValue = Integer.parseInt(quantityText);
                if (quantityValue <= 0)
                    errorMessage = msg;
            } catch (NumberFormatException nfe) {
                errorMessage = msg;
            }

            msg = "Konačna cijena mora biti decimalni broj veći od 0";
            try {
                finalPriceValue = Double.parseDouble(finalPriceText);
                if (finalPriceValue <= 0.) {
                    if (errorMessage != null)
                        errorMessage += "\n" + msg;
                    else
                        errorMessage = msg;
                }
            } catch (NumberFormatException nfe) {
                if (errorMessage != null)
                    errorMessage += "\n" + msg;
                else
                    errorMessage = msg;
            }
        }

        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage, "Greške", JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.optionPaneExitCode = JOptionPane.OK_OPTION;
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewExternalOrderItemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewExternalOrderItemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewExternalOrderItemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewExternalOrderItemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewExternalOrderItemJDialog dialog = new NewExternalOrderItemJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JCheckBox fertigCBox;
    private javax.swing.JTextField finalPrice;
    private javax.swing.JLabel hourlyCost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minPerPiece;
    private javax.swing.JLabel pricePerPiece;
    private javax.swing.JTable pricingTable;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel tightLathing;
    private javax.swing.JLabel tightMilling;
    // End of variables declaration//GEN-END:variables
}
