/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewPriceJDialog.java
 *
 * Created on 09.02.2012., 21:52:59
 */
package stefanpresentationlayer.dialogs;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.application.Action;
import stefan.business.MaterialManager;
import stefan.business.objects.CalculationForm;
import stefan.business.objects.Material;
import stefan.business.objects.MaterialDetails;

/**
 *
 * @author Robert
 */
public class EditPriceJDialog extends javax.swing.JDialog {
    private List<MaterialDetails> materialDetails = new ArrayList<MaterialDetails>();
    private List<CalculationForm> calculationForms = new ArrayList<CalculationForm>();
    private Material selectedMaterial;
    DecimalFormat priceFormatter = new DecimalFormat("#0.##");
    /** Creates new form NewPriceJDialog */
    public EditPriceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Promjena Cijene");
        MaterialManager manager = new MaterialManager();
        materialDetails = manager.GetAllMaterialDetails();
        calculationForms = manager.GetAllCalculationForms();
        this.firePropertyChange("calculationForms", null, null);
        this.firePropertyChange("materialDetails", null, null);
    }
    
    public EditPriceJDialog(java.awt.Frame parent, boolean modal,int materialId){
        super(parent, modal);
        initComponents();
        setTitle("Promjena Cijene");
        MaterialManager manager = new MaterialManager();
        materialDetails = manager.GetAllMaterialDetails();
        calculationForms = manager.GetAllCalculationForms();
        this.firePropertyChange("calculationForms", null, null);
        this.firePropertyChange("materialDetails", null, null);
        selectedMaterial = manager.GetMaterialById(materialId);
        FillData();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        editPriceNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editPricePriceInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editcomboBoxMaterialDetails = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        editcomboBoxCalculationForm = new javax.swing.JComboBox();
        editBtnClick = new javax.swing.JButton();
        comboBoxCalculationRenderer1 = new stefanpresentationlayer.ComboBoxCalculationRenderer();
        comboBoxMaterialDetailsRenderer1 = new stefanpresentationlayer.ComboBoxMaterialDetailsRenderer();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(EditPriceJDialog.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        editPriceNameInput.setText(resourceMap.getString("editPriceNameInput.text")); // NOI18N
        editPriceNameInput.setName("editPriceNameInput"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        editPricePriceInput.setText(resourceMap.getString("editPricePriceInput.text")); // NOI18N
        editPricePriceInput.setName("editPricePriceInput"); // NOI18N
        editPricePriceInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editPricePriceInputKeyTyped(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        editcomboBoxMaterialDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editcomboBoxMaterialDetails.setName("editcomboBoxMaterialDetails"); // NOI18N
        editcomboBoxMaterialDetails.setRenderer(comboBoxMaterialDetailsRenderer1);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${materialDetails}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, editcomboBoxMaterialDetails);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        editcomboBoxCalculationForm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editcomboBoxCalculationForm.setName("editcomboBoxCalculationForm"); // NOI18N
        editcomboBoxCalculationForm.setRenderer(comboBoxCalculationRenderer1);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${calculationForms}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, editcomboBoxCalculationForm);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getActionMap(EditPriceJDialog.class, this);
        editBtnClick.setAction(actionMap.get("editBtnClick")); // NOI18N
        editBtnClick.setText(resourceMap.getString("editBtnClick.text")); // NOI18N
        editBtnClick.setName("editBtnClick"); // NOI18N

        comboBoxCalculationRenderer1.setName("comboBoxCalculationRenderer1"); // NOI18N

        comboBoxMaterialDetailsRenderer1.setName("comboBoxMaterialDetailsRenderer1"); // NOI18N

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editPriceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editPricePriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editcomboBoxMaterialDetails, 0, 142, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editBtnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancel))
                                    .addComponent(editcomboBoxCalculationForm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCalculationRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMaterialDetailsRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPriceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPricePriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(comboBoxMaterialDetailsRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(comboBoxCalculationRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(editcomboBoxMaterialDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(editcomboBoxCalculationForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBtnClick)
                            .addComponent(btnCancel))
                        .addContainerGap())))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editPricePriceInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPricePriceInputKeyTyped
        ValidateTextField(evt);
    }//GEN-LAST:event_editPricePriceInputKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditPriceJDialog dialog = new EditPriceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private stefanpresentationlayer.ComboBoxCalculationRenderer comboBoxCalculationRenderer1;
    private stefanpresentationlayer.ComboBoxMaterialDetailsRenderer comboBoxMaterialDetailsRenderer1;
    private javax.swing.JButton editBtnClick;
    private javax.swing.JTextField editPriceNameInput;
    private javax.swing.JTextField editPricePriceInput;
    private javax.swing.JComboBox editcomboBoxCalculationForm;
    private javax.swing.JComboBox editcomboBoxMaterialDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the materialDetails
     */
    public List<MaterialDetails> getMaterialDetails() {
        return materialDetails;
    }

    /**
     * @param materialDetails the materialDetails to set
     */
    public void setMaterialDetails(List<MaterialDetails> materialDetails) {
        this.materialDetails = materialDetails;
    }

    /**
     * @return the calculationForms
     */
    public List<CalculationForm> getCalculationForms() {
        return calculationForms;
    }

    /**
     * @param calculationForms the calculationForms to set
     */
    public void setCalculationForms(List<CalculationForm> calculationForms) {
        this.calculationForms = calculationForms;
    }
    
    private boolean IsMoreThenOneDotInField(JTextField field) {
        if (field.getText().contains(",")) {
            return true;
        } else {
            return false;
        }
    }

    private void ValidateTextField(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            super.processKeyEvent(evt);
        } else if ((",".indexOf(c) > -1) && (!IsMoreThenOneDotInField((JTextField) evt.getSource()))) {
            super.processKeyEvent(evt);
        } else {
            evt.consume();
            return;
        }
    }

    @Action
    public void editBtnClick() {
        if(editPriceNameInput.getText().length()==0 || editPricePriceInput.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Popunite sva prazna polja","Greška",JOptionPane.ERROR_MESSAGE);
        }else{
            MaterialManager manager = new MaterialManager();
            try {
                manager.UpdatePrice(selectedMaterial.getIdShape(),(CalculationForm)editcomboBoxCalculationForm.getSelectedItem(),
                        (MaterialDetails)editcomboBoxMaterialDetails.getSelectedItem(),editPriceNameInput.getText().trim(),
                        BigDecimal.valueOf(Double.valueOf(editPricePriceInput.getText().trim().replace(",","."))));
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }

    private void FillData() {
        editPriceNameInput.setText(selectedMaterial.getName());
        editPricePriceInput.setText((priceFormatter.format(selectedMaterial.getEuroPerKg())));
        editcomboBoxCalculationForm.setSelectedIndex(GetCalcFormIndex());
        editcomboBoxMaterialDetails.setSelectedIndex(GetMaterialDetailsIndex());
    }

    private int GetCalcFormIndex() {
        for(CalculationForm c : calculationForms){
            if (c.getIdCalculationForm()==selectedMaterial.getCalculationForm().getIdCalculationForm()){
                return (c.getIdCalculationForm()-1);
            }
        }
        return 0;
    }

    private int GetMaterialDetailsIndex() {
        for(MaterialDetails m : materialDetails){
            if(m.getIdMaterialDetails() == selectedMaterial.getMaterialDetails().getIdMaterialDetails()){
                return (m.getIdMaterialDetails()-1);
            }
        }
        return 0;
    }
}
