/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewPriceJDialog.java
 *
 * Created on 09.02.2012., 21:52:59
 */
package stefanpresentationlayer.dialogs;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.application.Action;
import stefan.business.MaterialManager;
import stefan.business.objects.CalculationForm;
import stefan.business.objects.Material;
import stefan.business.objects.MaterialDetails;

/**
 *
 * @author Robert
 */
public class NewPriceJDialog extends javax.swing.JDialog {
    private List<MaterialDetails> materialDetails = new ArrayList<MaterialDetails>();
    private List<CalculationForm> calculationForms = new ArrayList<CalculationForm>();
    /** Creates new form NewPriceJDialog */
    public NewPriceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Novi Unos");
        MaterialManager manager = new MaterialManager();
        materialDetails = manager.GetAllMaterialDetails();
        calculationForms = manager.GetAllCalculationForms();
        this.firePropertyChange("calculationForms", null, null);
        this.firePropertyChange("materialDetails", null, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        newPriceNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        newPricePriceInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxMaterialDetails = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboBoxCalculationForm = new javax.swing.JComboBox();
        comboBoxCalculationRenderer1 = new stefanpresentationlayer.ComboBoxCalculationRenderer();
        comboBoxMaterialDetailsRenderer1 = new stefanpresentationlayer.ComboBoxMaterialDetailsRenderer();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getResourceMap(NewPriceJDialog.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        newPriceNameInput.setText(resourceMap.getString("newPriceNameInput.text")); // NOI18N
        newPriceNameInput.setName("newPriceNameInput"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        newPricePriceInput.setText(resourceMap.getString("newPricePriceInput.text")); // NOI18N
        newPricePriceInput.setName("newPricePriceInput"); // NOI18N
        newPricePriceInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPricePriceInputKeyTyped(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        comboBoxMaterialDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMaterialDetails.setName("comboBoxMaterialDetails"); // NOI18N
        comboBoxMaterialDetails.setRenderer(comboBoxMaterialDetailsRenderer1);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${materialDetails}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboBoxMaterialDetails);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stefanpresentationlayer.StefanPresentationLayerApp.class).getContext().getActionMap(NewPriceJDialog.class, this);
        jButton1.setAction(actionMap.get("saveNewPrice")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        comboBoxCalculationForm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCalculationForm.setName("comboBoxCalculationForm"); // NOI18N
        comboBoxCalculationForm.setRenderer(comboBoxCalculationRenderer1);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${calculationForms}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, comboBoxCalculationForm);
        bindingGroup.addBinding(jComboBoxBinding);

        comboBoxCalculationRenderer1.setName("comboBoxCalculationRenderer1"); // NOI18N

        comboBoxMaterialDetailsRenderer1.setName("comboBoxMaterialDetailsRenderer1"); // NOI18N

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCalculationRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPricePriceInput, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(newPriceNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxMaterialDetailsRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addComponent(comboBoxCalculationForm, 0, 192, Short.MAX_VALUE)
                            .addComponent(comboBoxMaterialDetails, 0, 192, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newPriceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newPricePriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxMaterialDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboBoxCalculationForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(comboBoxMaterialDetailsRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(comboBoxCalculationRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnCancel))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPricePriceInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPricePriceInputKeyTyped
        ValidateTextField(evt);
    }//GEN-LAST:event_newPricePriceInputKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPriceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewPriceJDialog dialog = new NewPriceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox comboBoxCalculationForm;
    private stefanpresentationlayer.ComboBoxCalculationRenderer comboBoxCalculationRenderer1;
    private javax.swing.JComboBox comboBoxMaterialDetails;
    private stefanpresentationlayer.ComboBoxMaterialDetailsRenderer comboBoxMaterialDetailsRenderer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField newPriceNameInput;
    private javax.swing.JTextField newPricePriceInput;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the materialDetails
     */
    public List<MaterialDetails> getMaterialDetails() {
        return materialDetails;
    }

    /**
     * @param materialDetails the materialDetails to set
     */
    public void setMaterialDetails(List<MaterialDetails> materialDetails) {
        this.materialDetails = materialDetails;
    }

    /**
     * @return the calculationForms
     */
    public List<CalculationForm> getCalculationForms() {
        return calculationForms;
    }

    /**
     * @param calculationForms the calculationForms to set
     */
    public void setCalculationForms(List<CalculationForm> calculationForms) {
        this.calculationForms = calculationForms;
    }
    
    private boolean IsMoreThenOneDotInField(JTextField field) {
        if (field.getText().contains(",")) {
            return true;
        } else {
            return false;
        }
    }

    private void ValidateTextField(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            super.processKeyEvent(evt);
        } else if ((",".indexOf(c) > -1) && (!IsMoreThenOneDotInField((JTextField) evt.getSource()))) {
            super.processKeyEvent(evt);
        } else {
            evt.consume();
            return;
        }
    }

    @Action
    public void saveNewPrice() {
        if(newPriceNameInput.getText().length()==0 || newPricePriceInput.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Popunite sva prazna polja","Greška",JOptionPane.ERROR_MESSAGE);
        }else{
            Material m = new Material();
            m.setCalculationForm((CalculationForm)comboBoxCalculationForm.getSelectedItem());
            m.setEuroPerKg(BigDecimal.valueOf(Double.parseDouble(newPricePriceInput.getText().toString().replace(",", "."))));
            m.setMaterialDetails((MaterialDetails)comboBoxMaterialDetails.getSelectedItem());
            m.setName(newPriceNameInput.getText().toString());
            
            MaterialManager manager = new MaterialManager();
            try {
                 manager.SaveMaterial(m);
                 this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Pogreška " + e.toString(), "Greška",JOptionPane.ERROR_MESSAGE);
            }           
        }
    }
}
