jLabel1.text=Broj Nacrta:
designNumberTF.text=
btnFindDesign.text=Prona\u0111i
jLabel17.text=Naziv nacrta:
jLabel18.text=Identitet:
jLabel19.text=Klasa:
jLabel16.text=Broj nacrta:
jLabel20.text=Datum:
jLabel21.text=1 
jLabel22.text=2 
jLabel36.text=500 
jLabel37.text=Povisi sve cijene za postotak:
jButton1.text=Povisi
btnSaveChanges.text=Spremi
btnCancel.text=Odustani
desigDateInput.text=
jLabel2.text=Tokarenje/Glodanje:
jLabel3.text=Niklanje:
jLabel38.text=Revizija:
jLabel38.AccessibleContext.accessibleName=Revizija:
jLabel2.AccessibleContext.accessibleDescription=
jLabel2.AccessibleContext.accessibleName=Tokarenje/Glodanje:
jLabel2.toolTipText=
daTokarenjeButton.text=Tokarenje
daNiklanjeButton.text=Da
neNiklanjeButton.text=Ne
createNewButton.text=Stvori Nacrt
daNlxButton.text=NLX
daGlodanjeButton.text=Glodanje
jLabel32.text=100 
jLabel27.text=15 
jLabel35.text=20 
jLabel33.text=50 
jLabel24.text=3 
jLabel26.text=5 
jLabel28.text=10 
jLabel23.text=1 
jLabel41.text=500
jLabel40.text=128
jLabel39.text=64
jLabel34.text=32
jLabel31.text=16
jLabel30.text=8
jLabel29.text=4
jLabel25.text=2 
jLabel4.text=Fertig:
daFertigButton.text=Da
neFertigButton.text=Ne
jLabel42.text=Minuta po kom:
jLabel43.text=Stezanje tok.:
jLabel44.text=Stezanje glod.:
jLabel45.text=Satnica
jLabel46.text=EUR/kom mat.:
