jLabel1.text=Broj narud\u017ebe
brojNarudzbeText.text=
jLabel2.text=Za firmu
partnerText.text=
jLabel3.text=Datum
jTable1.columnModel.title0=
jTable1.columnModel.title4=Revizija
jTable1.columnModel.title5=Naziv
jTable1.columnModel.title6=Identitet
jTable1.columnModel.title7=Klasa
jTable1.columnModel.title8=Niklanje
jTable1.columnModel.title9=T/G/N
jTable1.columnModel.title10=Datum
jTable1.columnModel.title11=Komada
jTable1.columnModel.title12=Cijena/Kom
#NOI18N
jLabel11.font=Tahoma 14 Bold
jLabel11.text=Ukupan Iznos:
#NOI18N
priceLbl.font=Tahoma 14 Plain
cancelBtn.text=Odustani
createOrderBtn.text=Uvezi Narud\u017ebu
#NOI18N
deleteBtn.icon=/stefanpresentationlayer/resources/cross_48.png
jTable1.columnModel.title13=Ukupna cijena
jTable1.columnModel.title3=Pozicija
jTable1.columnModel.title1=Broj nacrta
