#NOI18N
jLabel1.font=Segoe UI 24 12-Plain-24
confirmButton.toolTipText=
confirmButton.text=Potvrdi
city.toolTipText=
jLabel7.text=Grad
jLabel6.text=PDV ID. BR.
jLabel5.text=Pbr. i grad
jLabel4.text=Adresa dobavlja\u010da
jLabel3.text=Kratki naziv dobavlja\u010da
jLabel2.text=Naziv dobavlja\u010da
name.toolTipText=
jLabel1.text=Upis novog vanjskog dobavlja\u010da
jLabel6.toolTipText=
