jLabel1.text=minuta po kom
jLabel2.text=stezanje tokarenje
jLabel3.text=stezanje glodanje
jLabel4.text=satnica
jLabel5.text=\u20ac/kom
jLabel6.text=Koli\u010dina
jLabel7.text=Cijena po komadu
confirmBtn.text=Potvrdi
cancelBtn.text=Odustani
#NOI18N
jPanel1.border.lineColor=204, 204, 204
#NOI18N
jPanel6.border.lineColor=204, 204, 204
fertig.text=
jLabel8.text=fertig
