jLabel1.text=Minuta po komadu
minPerPiece.text=7
fertigCBox.text=Fertig
tightLathing.text=2
jLabel2.text=Stezanje tokarenje
tightMilling.text=0,0
jLabel3.text=Stezanje glodanje
hourlyCost.text=33,0
jLabel4.text=Satnica
pricePerPiece.text=1,55
jLabel5.text=\u20ac/kom (materijal)
#NOI18N
jPanel1.border.lineColor=204, 204, 204
#NOI18N
jPanel4.border.lineColor=204, 204, 204
quantity.text=
finalPrice.text=
jLabel6.text=Koli\u010dina
jLabel7.text=Kona\u010dna cijena
cancelBtn.text=Odustani
confirmBtn.text=Potvrdi
