#NOI18N
jLabel1.font=Segoe UI 24 12-Plain-24
confirmButton.toolTipText=
confirmButton.text=Potvrdi
city.toolTipText=
jLabel7.text=Grad
jLabel6.text=PDV ID. BR.
jLabel5.text=Pbr.
jLabel4.text=Adresa dobavlja\u010da
jLabel3.text=Kratki naziv dobavlja\u010da
jLabel2.text=Naziv dobavlja\u010da
name.toolTipText=
jLabel1.text=Upis novog vanjskog dobavlja\u010da
jLabel6.toolTipText=
jTable1.columnModel.title3=Title 4
#NOI18N
jPanel3.border.lineColor=204, 204, 204
cancelBtn.text=Odustani
jLabel8.text=Upisani vanjski dobavlja\u010di
#NOI18N
jLabel8.font=Tahoma-Plain-20
externalSuppliersTab.columnModel.title2=PDV ID. BR.
externalSuppliersTab.columnModel.title1=Grad
externalSuppliersTab.columnModel.title0=Naziv
cancelEditBtn.text=Odustani od ure\u0111ivanja
deleteSupplierBtn.text=Obri\u0161i odabranog dobavlja\u010da
